SELECT  b.HISTORY_ID,
        CASE 
            WHEN (b.END_DATE - b.START_DATE + 1) >= 90 
                THEN a.DAILY_FEE * (b.END_DATE - b.START_DATE + 1) 
                * (SELECT 1 - (DISCOUNT_RATE/100) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상')
            WHEN (b.END_DATE - b.START_DATE + 1) >= 30 
                THEN a.DAILY_FEE * (b.END_DATE - b.START_DATE + 1) 
                * (SELECT 1 - (DISCOUNT_RATE/100) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상')
            WHEN (b.END_DATE - b.START_DATE + 1) >= 7 
                THEN a.DAILY_FEE * (b.END_DATE - b.START_DATE + 1) 
                * (SELECT 1 - (DISCOUNT_RATE/100) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상')
            ELSE a.DAILY_FEE * (b.END_DATE - b.START_DATE + 1)
        END AS FEE
  FROM  CAR_RENTAL_COMPANY_CAR a
      , CAR_RENTAL_COMPANY_RENTAL_HISTORY b
 WHERE  b.CAR_ID = a.CAR_ID
   AND  a.CAR_TYPE = '트럭'
 ORDER  BY FEE DESC, HISTORY_ID DESC