WITH HOURS AS (
    SELECT LEVEL - 1 AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
)
SELECT H.HOUR, COALESCE(COUNT(AO.DATETIME), 0) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS AO
    ON H.HOUR = TO_NUMBER(TO_CHAR(AO.DATETIME, 'HH24'))
GROUP BY H.HOUR
ORDER BY H.HOUR;
