-- 코드를 입력하세요
SELECT UGU.USER_ID USER_ID, UGU.NICKNAME NICKNAME, SUM(UGB.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD UGB
RIGHT JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY 3

-- SELECT UGU.USER_ID, UGU.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES 
-- FROM USED_GOODS_BOARD A
-- LEFT JOIN USED_GOODS_USER UGU
-- ON A.WRITER_ID = UGU.USER_ID
-- WHERE A.STATUS = 'DONE'
-- GROUP BY UGU.USER_ID, UGU.NICKNAME
-- HAVING SUM(A.PRICE) > = 700000 
-- ORDER BY SUM(A.PRICE)
-- ;