-- 코드를 입력하세요
-- SELECT MEMBER_NAME, REVIEW_TEXT, TEVIEW_DATE

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, RR.RIEVEW_DATE
FROM MEMBER_PROFILE MP
JOIN
( 
    SELECT MEMBER_ID, REVIEW_TEXT, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') RIEVEW_DATE
    FROM REST_REVIEW 
    WHERE MEMBER_ID = (
        SELECT MEMBER_ID FROM (
            SELECT MEMBER_ID, COUNT(REVIEW_TEXT)
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY COUNT(REVIEW_TEXT) DESC
        )
        WHERE ROWNUM <= 1
    )
) RR
ON MP.MEMBER_ID = RR.MEMBER_ID
ORDER BY RR.RIEVEW_DATE ASC, RR.REVIEW_TEXT ASC



