SELECT ANIMAL_ID, NAME
FROM (
    SELECT I.ANIMAL_ID, I.NAME, ROWNUM AS RN
    FROM (
        SELECT I.ANIMAL_ID, I.NAME, I.DATETIME
        FROM ANIMAL_INS I
        JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
        WHERE I.DATETIME > O.DATETIME
        ORDER BY I.DATETIME ASC
    ) I
)
WHERE RN > 0;