-- 코드를 입력하세요
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCR JOIN  CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
USING(CAR_ID)
WHERE CRCR.CAR_TYPE = '세단'
AND TO_CHAR(CRCRH.START_DATE, 'MM') = '10'
ORDER BY CAR_ID DESC;
